version: '3'

services:
    database:
        image: postgres
        container_name: database
        environment:
            - POSTGRES_USER=awesome_user
            - POSTGRES_PASSWORD=awesome_password
            - POSTGRES_DB=csgo_ban

        volumes:
            - database-volume:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        networks:
            - shared-network
        restart: on-failure
    api:
        depends_on:
            - database
        environment:
            - NODE_ENV=development
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/app
        container_name: api
        expose:
            - '4000'
        ports:
            - '4000:4000'
        command: npm run dev
        networks:
            - shared-network
        restart: on-failure

volumes:
    database-volume:

networks:
    shared-network:
