export const KNIFE_CATEGORIES = [
    'Talon Knife',
    'Ursus Knife',
    'Navaja Knife',
    'Classic Knife',
    'Falchion Knife',
    'Karambit',
    'Paracord Knife',
    'Nomad Knife',
    'Stiletto Knife',
    'Survival Knife',
    'Bowie Knife',
    'Shadow Daggers',
    'Gut Knife',
    'Skeleton Knife',
    'Butterfly Knife',
    'Huntsman Knife',
    'M9 Bayonet',
    'Flip Knife',
    'Bayonet',
];
